using MonoRogue.Data;
using SadRogue.Primitives;

namespace MonoRogue.Core;

/// <summary>
/// Populates the world with entities for one dungeon level: stairs (except on the top and
/// bottom levels), monsters, items, and treasure. Terrain must already be generated by an
/// <see cref="IDungeonLayoutGenerator"/>. The <see cref="Random"/> instance is injected so
/// placement is reproducible for a given (seed, depth) pair.
/// </summary>
public sealed class MapGenerator
{
    private readonly EntityFactory _factory;
    private readonly SpatialMap _spatial;
    private Random _rng;

    public MapGenerator(EntityFactory factory, SpatialMap spatial, Random rng)
    {
        _factory = factory;
        _spatial = spatial;
        _rng = rng;
    }

    /// <summary>Swaps the RNG used for placement, so each level generates from its own seed.</summary>
    public void Reset(Random rng)
    {
        _rng = rng;
    }

    /// <summary>
    /// Generates the contents of one dungeon level (stairs, treasure, items, monsters).
    /// The player entity must already exist (it is skipped by placement). Returns the player's
    /// entry cell: the up-stair on levels below the first, otherwise the map center.
    /// </summary>
    public Point GenerateNewLevel(int depth, int maxDepth)
    {
        Point? entry = null;

        if (depth > 1)
        {
            var up = _spatial.GetRandomOpenCell(_rng);
            if (up is Point upStair)
            {
                _factory.CreateStairs(upStair, new CoreGlyph('<', GameConstants.ArgbCyan, GameConstants.ArgbBlack), StairDirection.Up);
                entry = upStair;
            }
        }

        if (depth < maxDepth)
        {
            var down = entry is Point e
                ? _spatial.GetRandomOpenCell(_rng, e)
                : _spatial.GetRandomOpenCell(_rng);
            if (down is Point downStair)
            {
                _factory.CreateStairs(downStair, new CoreGlyph('>', GameConstants.ArgbCyan, GameConstants.ArgbBlack), StairDirection.Down);
            }
        }

        var entryCell = entry ?? _spatial.GetCenter();

        CreateTreasure(entryCell);

        var itemTemplates = ItemDataLoader.LoadDefinitionsFromDefaultSearchPaths();
        foreach (var template in itemTemplates)
        {
            CreateItem(template, entryCell);
        }

        var templates = MonsterDataLoader.LoadDefinitionsFromDefaultSearchPaths();
        if (templates.Count == 0)
        {
            CreateGoblin(entryCell);
            CreateDragon(entryCell);
        }
        else
        {
            foreach (var template in templates)
            {
                CreateMonster(template, entryCell);
            }
        }

        return entryCell;
    }

    public void CreateInitialPlayer(Point spawn)
    {
        _factory.CreatePlayer(
            spawn,
            new CoreGlyph('@', GameConstants.ArgbWhite, GameConstants.ArgbBlack),
            new Health { Current = GameConstants.DefaultPlayerHealth, Max = GameConstants.DefaultPlayerHealth },
            GameConstants.DefaultPlayerAttack);
    }

    private void CreateItem(ItemDefinition definition, Point exclude)
    {
        var position = _spatial.GetRandomWalkableCell(_rng, exclude);
        if (position is not Point p)
        {
            return;
        }

        _factory.CreateItem(
            p,
            new CoreGlyph(definition.Glyph, definition.ForegroundArgb, definition.BackgroundArgb),
            definition.Kind,
            definition.Name,
            definition.Magnitude);
    }

    private void CreateMonster(MonsterDefinition definition, Point exclude)
    {
        var position = _spatial.GetRandomOpenCell(_rng, exclude);
        if (position is not Point p)
        {
            return;
        }

        _factory.CreateMonster(
            p,
            new CoreGlyph(definition.Glyph, definition.ForegroundArgb, definition.BackgroundArgb),
            new Health { Current = GameConstants.DefaultMonsterHealth, Max = GameConstants.DefaultMonsterHealth },
            Math.Max(1, definition.Damage),
            new MonsterBehavior { Type = definition.Behavior, Range = definition.Range, SpecialEnergyCost = definition.SpecialEnergyCost },
            definition.GainPerTurn,
            definition.ActionCost,
            definition.Experience);
    }

    private void CreateTreasure(Point exclude)
    {
        var position = _spatial.GetRandomOpenCell(_rng, exclude);
        if (position is not Point p)
        {
            return;
        }

        _factory.CreateBlocker(p, new CoreGlyph('v', GameConstants.ArgbYellow, GameConstants.ArgbBlack));
    }

    private void CreateGoblin(Point exclude)
    {
        CreateMonster('g', GameConstants.ArgbRed, GameConstants.DefaultEnergyPerTurn, GameConstants.DefaultActionCost, exclude);
    }

    private void CreateDragon(Point exclude)
    {
        // Dragon gains energy like a normal actor but can spend more on special actions.
        CreateMonster('D', GameConstants.ArgbOrangeRed, GameConstants.DefaultEnergyPerTurn, GameConstants.DefaultActionCost, exclude);
    }

    private void CreateMonster(int glyphCode, int foregroundArgb, int gainPerTurn, int actionCost, Point exclude)
    {
        var position = _spatial.GetRandomOpenCell(_rng, exclude);
        if (position is not Point p)
        {
            return;
        }

        _factory.CreateMonster(
            p,
            new CoreGlyph((char)glyphCode, foregroundArgb, GameConstants.ArgbBlack),
            new Health
                {
                    Current = GameConstants.DefaultMonsterHealth
                    , Max = GameConstants.DefaultMonsterHealth
                },
            glyphCode == 'D' ? GameConstants.DragonAttack : GameConstants.DefaultMonsterAttack,
            EntityFactory.InferBehavior((char)glyphCode),
            gainPerTurn,
            actionCost,
            glyphCode == 'D' ? GameConstants.DragonExperience : GameConstants.DefaultMonsterExperience
            );
    }
}
